apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: fastapi
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fastapi
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/configuration-es-net: "true"
        io.kompose.service: fastapi
    spec:
      containers:
        - image: skeletyon/fastapi_projet:v1
          name: fastapi-container
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
